Rails:
  Enabled: true

AllCops:
  TargetRubyVersion: 2.1

Metrics/LineLength:
  Max: 140

# Offense count: 34
# Configuration parameters: CountComments.
Metrics/MethodLength:
  Max: 60

# Offense count: 11
Metrics/CyclomaticComplexity:
  Max: 13

# Offense count: 10
Metrics/PerceivedComplexity:
  Max: 14

# Offense count: 15
Metrics/AbcSize:
  Max: 60

Metrics/ModuleLength:
  Max: 300

Metrics/ClassLength:
  Max: 300

Style/Documentation:
  Enabled: false

Rails/HttpPositionalArguments:
  Enabled: false

# Only use it if Redmine switched to Rails 5
Rails/ApplicationRecord:
  Enabled: false

Metrics/BlockLength:
  Max: 50
